### ISSUE TITLE
listStationsWithAdvancedSearch No paging provided

### ISSUE THREAD

**Issue by ChildProdigy** [sfuhrm/radiobrowser4j#126]
https://de1.api.radio-browser.info/#General

Advanced station search

http://de1.api.radio-browser.info/json/stations/search
The official API provides offset and limit

At present, the lib has been hardcoded to prevent users from operating it, 
but sometimes users want to control how much data is preloaded.

**Comment by sfuhrm** [comment]
There are multiple levels to see here.
On one hand, the library does not provide a way to support paging for the `listStationsWithAdvancedSearch()` call. Since other calls have the paging possibility, this call should also have it.

On the other hand, internally usually there is paging used instead of fetching all data with no way for the user to change the fetch size.

The HTTP API usually has a default of limit 100000.

Can you explain to me the use case why it makes sense to increase the default fetch-limit for the user?

**Comment by sfuhrm** [comment]
I've added support for paging in the advanced search call.
Besides that I also fixed conflicts with the explicit paging and the implicit paging that were in the code for some calls.

**Comment by ChildProdigy** [comment]
At present, Lib will automatically use the stream method to load, but some third-party components will control the loading timing themselves. What needs to be returned is the data array, so there is this requirement.

**Comment by sfuhrm** [comment]
At the moment the code re-uses the stream part and does the paging internally.
Added in the commt [b698f81](https://github.com/sfuhrm/radiobrowser4j/commit/b698f8122250639b45636b7ed3b02406fd8eb4b1)  there's now the advanced search pagable. This is now restricting the *view* of the returned stream, not exactly controlling *how* the library code fetches data.

The libraries main job is to abstract from how things look on HTTP and provide a comfortable Java class view of that. Timeouts are handled with one central mechanism in the library.
My gut feeling is that fine-grain control would break the abstraction.

So if you could wish something, what would it be?

**Comment by ChildProdigy** [comment]
I want

int page = 0;
int offset = 0;
int limit = 10;

AdvancedSearch advancedTWSearch = AdvancedSearch.builder();
advancedTWSearch.offset(offset).limit(limit);   // (offset = page * limit;)

List<Station> stations = radioBrowser.listStationsWithAdvancedSearch(advancedTWSearch, page);  // return page data

**Comment by sfuhrm** [comment]
To summarize, your examples are returning `List` instances with explicit paging boundaries. The current advanced search only returns `Stream` instances with automatic paging that has no possibility of intervention in the page size.

Since the other calls are also providing List variants, the most obvious solution is to provide also an advanced search call with paging and a List return.

**Comment by sfuhrm** [comment]
Thanks for the input here, that's appreciated!
All changes discussed so far are in todays release 'Release 3.1.0'.
